baseURL = "https://blessmeapp.com/"
languageCode = "en-us"
theme = "hugo-appyness"

DefaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    title = "Your faith is worthy."
    languageName = "English"
    heading = "Your faith is worthy. Share it."
    weight = 1
  [languages.fr]
    title = "Votre foi est précieuse."
    languageName = "French"
    heading = "Your faith is worthy. Share it."
    weight = 2
